version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn dev --host"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
