name: Create Tag

on:
  push:
    branches: [ 'development' ]
  workflow_run:
    workflows: [ "GitHub Packages" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@1.2.3
      # with:
      #   changelog_structure: ${{ secrets.GITHUB_TOKEN }}
